# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Document-Assist2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://rfprfq.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2c478b8ca55d4b01840306b48adaeb47 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f614f94252e841e2b54ba906621dc7a6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: rfprfq.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2c478b8ca55d4b01840306b48adaeb47 }}/https:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Document-Assist2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4694111e39fb4f25812a1bb3a80c6ee1 }}
        images: 'rfprfq.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2c478b8ca55d4b01840306b48adaeb47 }}/https:${{ github.sha }}'